In [4]:
import os
import sys
import copy
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from src.data.datahandler import DataHandler
import os
import logging
import time

In [5]:
input_file = os.path.join("D:\\", "projects", "nmf_py", "data", "Dataset-BatonRouge-con.csv")
uncertainty_file = os.path.join("D:\\", "projects", "nmf_py", "data", "Dataset-BatonRouge-unc.csv")
output_path = os.path.join("D:\\", "projects", "nmf_py", "output", "BatonRouge")

In [6]:
quantile = 0.98
drop_max = True
drop_min = False

index_col = "Date"

In [7]:
dh = DataHandler(
        input_path=input_file,
        uncertainty_path=uncertainty_file,
        output_path=output_path,
        index_col=index_col
    )
dh.input_data

01-Dec-22 14:04:29 - Input and output configured successfully


124-Trimethylbenzene  224-Trimethylpentane  \
Date                                                         
6/1/2005 6:00               0.530000              1.560001   
6/2/2005 3:00               2.730002              4.650003   
6/2/2005 6:00               1.290001              4.660003   
6/3/2005 3:00               4.170003              6.790004   
6/4/2005 3:00               1.580001              2.550002   
...                              ...                   ...   
9/24/2006 6:00              0.290000              2.240001   
9/25/2006 6:00              0.550000              1.760001   
9/26/2006 3:00              0.680000              1.390001   
9/26/2006 6:00              1.140001              2.760002   
9/28/2006 3:00              2.600002              4.110003   

                234-Trimethylpentane  23-Dimethylbutane  23-Dimethylpentane  \
Date                                                                          
6/1/2005 6:00               0.460000           0.580000            0.230000   
6/2/2005 3:00               2.550002           1.440001            0.880001   
6/2/2005 6:00               1.270001           2.070001            0.970001   
6/3/2005 3:00               2.180001           0.800001            1.030001   
6/4/2005 3:00               0.810001           1.000001            0.540000   
...                              ...                ...                 ...   
9/24/2006 6:00              0.620000           4.610003            0.600000   
9/25/2006 6:00              0.470000           3.120002            0.400000   
9/26/2006 3:00              0.460000           0.410000            0.005000   
9/26/2006 6:00              0.860001           0.990001            0.470000   
9/28/2006 3:00              1.460001           6.260004            0.830001   

                2-Methylheptane  3-Methylhexane  3-Methylpentane  Acetylene  \
Date                                                                          
6/1/2005 6:00             0.370        0.450000         2.460002   2.060001   
6/2/2005 3:00             0.760        1.840001         3.680002   2.620002   
6/2/2005 6:00             0.550        1.480001         3.880002   2.490002   
6/3/2005 3:00             0.790        2.120001         4.940003   4.490003   
6/4/2005 3:00             0.380        1.080001         2.110001   2.080001   
...                         ...             ...              ...        ...   
9/24/2006 6:00            0.170        0.970001        11.940007   0.410000   
9/25/2006 6:00            0.300        1.130001         6.330004   1.360001   
9/26/2006 3:00            0.005        1.060001         0.920001   1.360001   
9/26/2006 6:00            0.300        0.990001         2.090001   3.480002   
9/28/2006 3:00            0.670        1.760001        15.260010   3.090002   

                 Benzene  ...  O-Ethyltoluene  O-Xylene    Propane  Propylene  \
Date                      ...                                                   
6/1/2005 6:00   1.980001  ...        0.005000  1.020001  17.760011  19.200012   
6/2/2005 3:00   3.560002  ...        0.730000  2.160001  14.370009   6.200004   
6/2/2005 6:00   3.340002  ...        0.410000  1.200001  19.690012   4.210003   
6/3/2005 3:00   5.400003  ...        1.330001  3.510002  15.920010   3.680002   
6/4/2005 3:00   2.920002  ...        0.610000  1.600001  14.160009   2.540002   
...                  ...  ...             ...       ...        ...        ...   
9/24/2006 6:00  3.250002  ...        0.090000  0.470000  39.240025   4.520003   
9/25/2006 6:00  1.150001  ...        0.005000  0.590000   8.190005   1.060001   
9/26/2006 3:00  1.180001  ...        0.005000  0.530000   4.750003   0.800001   
9/26/2006 6:00  2.040001  ...        0.410000  1.040001  10.040006   2.080001   
9/28/2006 3:00  3.950002  ...        0.550000  2.100001  19.730012   3.480002   

                 Styrene    Toluene  Trans-2-Butene  Trans-2-Pentene  \
Date                       

In [5]:
dh.remove_outliers(quantile=quantile, drop_min=drop_min, drop_max=drop_max)
dh.input_data_processed[:2]

08-Nov-22 12:07:22 - Removed outliers for quantile: 0.98, min values: False, max values: True
08-Nov-22 12:07:22 - Original row count: 307, Updated row count: 224


array([[1.2900008e+00, 4.6600027e+00, 1.2700008e+00, 2.0700014e+00,
        9.7000062e-01, 5.5000037e-01, 1.4800010e+00, 3.8800025e+00,
        2.4900014e+00, 3.3400021e+00, 4.0000024e-01, 7.0000046e-01,
        1.5730010e+01, 9.2000055e-01, 3.9000025e+00, 8.2800055e+00,
        2.4420015e+01, 3.3400021e+00, 5.0000031e-03, 3.0900018e+00,
        2.0000012e-01, 8.7000054e-01, 2.7150017e+01, 4.3000028e-01,
        1.4400009e+00, 5.6200037e+00, 3.9000025e-01, 7.4000049e-01,
        1.1300007e+01, 2.8000018e-01, 4.0000024e-01, 4.1000026e-01,
        1.2000008e+00, 1.9690012e+01, 4.2100024e+00, 4.3000028e-01,
        6.1200037e+00, 5.3000033e-01, 1.3000008e+00, 2.3178396e+01,
        1.8867349e+02],
       [1.5800010e+00, 2.5500016e+00, 8.1000048e-01, 1.0000006e+00,
        5.4000032e-01, 3.8000023e-01, 1.0800006e+00, 2.1100013e+00,
        2.0800014e+00, 2.9200017e+00, 5.0000031e-03, 3.6000022e-01,
        2.0230013e+01, 1.2800008e+00, 6.2800040e+00, 8.7100058e+00,
        1.1040007e+01, 4

In [5]:
dh.min_values

124-Trimethylbenzene     0.005000
224-Trimethylpentane     0.061500
234-Trimethylpentane     0.005000
23-Dimethylbutane        0.005000
23-Dimethylpentane       0.005000
2-Methylheptane          0.005000
3-Methylhexane           0.005000
3-Methylpentane          0.081000
Acetylene                0.057000
Benzene                  0.088500
Cis-2-Butene             0.005000
Cis-2-Pentene            0.005000
Ethane                   0.385500
Ethylbenzene             0.030000
Ethylene                 0.133500
Isobutane                0.103500
Isopentane               0.375000
Isoprene                 0.005000
Isopropylbenzene         0.005000
M_P Xylene               0.070500
M-Diethylbenzene         0.005000
M-Ethyltoluene           0.005000
N-Butane                 0.247500
N-Decane                 0.005000
N-Heptane                0.031500
N-Hexane                 0.099000
N-Nonane                 0.005000
N-Octane                 0.005000
N-Pentane                0.106500
N-Propylbenzen

In [7]:
dh.max_values

124-Trimethylbenzene       5.470003
224-Trimethylpentane      13.560008
234-Trimethylpentane       4.410003
23-Dimethylbutane         10.500007
23-Dimethylpentane         3.310002
2-Methylheptane            2.480002
3-Methylhexane             7.780005
3-Methylpentane           29.100018
Acetylene                  8.070005
Benzene                    9.330006
Cis-2-Butene              21.510013
Cis-2-Pentene             19.130012
Ethane                    49.970031
Ethylbenzene               3.760002
Ethylene                  49.490031
Isobutane                 36.330023
Isopentane               125.500079
Isoprene                   9.420006
Isopropylbenzene           6.640004
M_P Xylene                13.050008
M-Diethylbenzene           1.740001
M-Ethyltoluene             4.670003
N-Butane                  56.230035
N-Decane                   1.760001
N-Heptane                  5.350003
N-Hexane                  92.560058
N-Nonane                   1.950001
N-Octane                   3

In [9]:
dh.input_data.max()

124-Trimethylbenzene      5.470003
224-Trimethylpentane     13.560008
234-Trimethylpentane      4.410003
23-Dimethylbutane        10.500007
23-Dimethylpentane        3.310002
2-Methylheptane           2.480002
3-Methylhexane            7.780005
3-Methylpentane          29.100018
Acetylene                 8.070005
Benzene                   9.330006
Cis-2-Butene             21.510013
Cis-2-Pentene            19.130012
Ethane                   49.970031
Ethylbenzene              3.760002
Ethylene                 49.490031
Isobutane                36.330023
Isopentane              125.500079
Isoprene                  9.420006
Isopropylbenzene          6.640004
M_P Xylene               13.050008
M-Diethylbenzene          1.740001
M-Ethyltoluene            4.670003
N-Butane                 56.230035
N-Decane                  1.760001
N-Heptane                 5.350003
N-Hexane                 92.560058
N-Nonane                  1.950001
N-Octane                  3.100002
N-Pentane           

In [5]:
dh.scale()
dh.input_data_processed[:2]

array([[9.6065871e-02, 8.7452471e-02, 1.0329171e-01, 5.4787993e-02,
        6.8078667e-02, 1.4747475e-01, 5.7234727e-02, 6.7226887e-02,
        2.1846555e-01, 1.5903890e-01, 2.2260067e-12, 1.1764705e-02,
        9.1561176e-02, 6.4606741e-02, 2.2530866e-01, 7.2755331e-01,
        2.4308944e-02, 1.2692513e-01, 7.2148112e-12, 6.3593008e-02,
        2.7590935e-11, 8.6816721e-02, 5.0201539e-02, 1.5099715e-01,
        8.5603110e-02, 1.8737757e-01, 2.0822622e-01, 1.2762520e-01,
        5.0699759e-02, 5.1198153e-11, 9.6322246e-02, 2.9641036e-11,
        1.5779094e-01, 2.2561865e-01, 7.6753670e-01, 5.0359715e-02,
        7.7464789e-02, 1.4936122e-11, 8.0752537e-02, 7.9946637e-02,
        1.8431342e-01],
       [4.9862763e-01, 3.2243347e-01, 5.7775253e-01, 1.3673177e-01,
        2.6475036e-01, 3.0505049e-01, 2.3601286e-01, 1.0994397e-01,
        2.9128736e-01, 3.3981696e-01, 7.0913740e-02, 5.9869278e-02,
        2.4367088e-01, 4.0730336e-01, 1.0226337e-01, 2.0594838e-01,
        1.0479675e-01, 2

In [6]:
import numpy as np

np.max(dh.input_data_processed, axis=0)

array([1.        , 0.99999994, 1.        , 1.        , 1.        ,
       0.99999994, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.99999994, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.99999994, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.99999994, 1.        ,
       1.        ], dtype=float32)

In [20]:


scale_test = np.subtract(dh.input_data_processed, dh.min_values.to_numpy())
scale_test.shape

(307, 41)

In [ ]:
scale_test = np.subtract(dh.input_data_processed, dh.min_values)).divide(dh.max_values - dh.min_values)